services:
  postgres:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword # You can change this, just update your .env.local
      POSTGRES_DB: mcrc_dev
    volumes:
      # This ensures your database data is saved in a named volume on your machine
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
